allowBuilds:
  '@cloudflare/workerd-linux-64': true
  '@cloudflare/workerd-linux-arm64': true
  '@next/swc-darwin-x64': true
  '@next/swc-linux-arm64-musl': true
  '@next/swc-linux-x64-gnu': true
  '@next/swc-win32-arm64-msvc': true
  '@next/swc-win32-x64-msvc': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
